package com.melocode.semin.controllers;

import com.melocode.semin.dao.ParticipationDAO;
import com.melocode.semin.dao.SeminaireDAO;
import com.melocode.semin.models.Participation;
import com.melocode.semin.models.Seminaire;
import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.geometry.Insets;
import javafx.scene.Scene;
import javafx.scene.chart.PieChart;
import javafx.scene.chart.ScatterChart;
import javafx.scene.chart.XYChart;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.FileChooser;
import javafx.stage.Modality;
import javafx.stage.Stage;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.List;

public class ParticipationCrudController {

    @FXML private TableView<Participation> tableView;
    @FXML private TableColumn<Participation, Integer> idColumn, seminaireIdColumn;
    @FXML private TableColumn<Participation, String> statutColumn, evaluationColumn, certificatColumn;
    @FXML private TableColumn<Participation, LocalDate> dateInscriptionColumn;
    @FXML private TextField statutField, evaluationField, certificatField, searchField;
    @FXML private ComboBox<String> seminaireComboBox;
    @FXML private Label coutLabel;
    @FXML private PieChart pieChart;
    @FXML private ScatterChart<String, Number> scatterChart;

    @FXML


    private void loadPieChartData() {
        ObservableList<PieChart.Data> pieChartData = FXCollections.observableArrayList(
                new PieChart.Data("présent", 40),
                new PieChart.Data("Inscrit", 30),
                new PieChart.Data("en attente", 20),
                new PieChart.Data("Non payé", 10)
        );
        pieChart.setData(pieChartData);
    }




    private ObservableList<Participation> participationList = FXCollections.observableArrayList();

    @FXML
    public void initialize() {
        // Initialize table columns
        idColumn.setCellValueFactory(cellData -> cellData.getValue().ID_ParticipationProperty().asObject());
        seminaireIdColumn.setCellValueFactory(cellData -> cellData.getValue().ID_SeminaireProperty().asObject());
        statutColumn.setCellValueFactory(cellData -> cellData.getValue().statutProperty());
        dateInscriptionColumn.setCellValueFactory(cellData -> cellData.getValue().dateInscriptionProperty());
        evaluationColumn.setCellValueFactory(cellData -> cellData.getValue().evaluationProperty());
        certificatColumn.setCellValueFactory(cellData -> cellData.getValue().certificatProperty());
        loadPieChartData();
        // Load seminars into ComboBox
        loadSeminars();
        // Load participations into TableView
        loadParticipations();
        // Initialize charts
        updateCharts();
    }

    private void loadSeminars() {
        SeminaireDAO seminarDAO = new SeminaireDAO();
        List<Seminaire> seminars = seminarDAO.getAllSeminaires();
        ObservableList<String> seminarNames = FXCollections.observableArrayList();
        for (Seminaire seminar : seminars) {
            seminarNames.add(seminar.getNom());
        }
        seminaireComboBox.setItems(seminarNames);
    }

    @FXML
    private void ajouterParticipation() {
        String statut = statutField.getText();
        String evaluation = evaluationField.getText();
        String certificat = certificatField.getText();
        String selectedSeminar = seminaireComboBox.getValue();

        if (statut.isEmpty() || selectedSeminar == null) {
            showAlert(Alert.AlertType.WARNING, "Validation Error", "Please fill in all the required fields.");
            return;
        }

        SeminaireDAO seminarDAO = new SeminaireDAO();
        Seminaire seminar = seminarDAO.getSeminarByName(selectedSeminar);

        if (seminar == null) {
            showAlert(Alert.AlertType.ERROR, "Seminar Error", "Selected seminar does not exist.");
            return;
        }

        Participation newParticipation = new Participation(
                0, // ID is generated by the database
                1, // ID_Employe (You can pass the actual employee ID here)
                seminar.getId(),
                statut,
                LocalDate.now(),
                evaluation,
                certificat
        );

        ParticipationDAO participationDAO = new ParticipationDAO();
        participationDAO.ajouterParticipation(newParticipation);

        loadParticipations();
        updateCharts();
    }

    @FXML
    private void modifierParticipation() {
        Participation selected = tableView.getSelectionModel().getSelectedItem();
        if (selected != null) {
            String statut = statutField.getText();
            String evaluation = evaluationField.getText();
            String certificat = certificatField.getText();
            String selectedSeminar = seminaireComboBox.getValue();

            if (statut.isEmpty() || selectedSeminar == null) {
                showAlert(Alert.AlertType.WARNING, "Validation Error", "Please fill in all the required fields.");
                return;
            }

            SeminaireDAO seminarDAO = new SeminaireDAO();
            Seminaire seminar = seminarDAO.getSeminarByName(selectedSeminar);

            if (seminar == null) {
                showAlert(Alert.AlertType.ERROR, "Seminar Error", "Selected seminar does not exist.");
                return;
            }

            selected.setStatut(statut);
            selected.setEvaluation(evaluation);
            selected.setCertificat(certificat);
            selected.setID_Seminaire(seminar.getId());

            ParticipationDAO participationDAO = new ParticipationDAO();
            participationDAO.modifierParticipation(selected);

            loadParticipations();
            updateCharts();
        } else {
            showAlert(Alert.AlertType.WARNING, "Selection Error", "Please select a participation to update.");
        }
    }

    @FXML
    private void supprimerParticipation() {
        Participation selected = tableView.getSelectionModel().getSelectedItem();
        if (selected != null) {
            ParticipationDAO participationDAO = new ParticipationDAO();
            participationDAO.supprimerParticipation(selected.getID_Participation());
            loadParticipations();
            updateCharts();
        } else {
            showAlert(Alert.AlertType.WARNING, "Selection Error", "Please select a participation to delete.");
        }
    }

    @FXML
    private void rechercherParticipation() {
        String keyword = searchField.getText().toLowerCase();
        ObservableList<Participation> filteredList = FXCollections.observableArrayList();

        for (Participation p : participationList) {
            if (p.getStatut().toLowerCase().contains(keyword) ||
                    p.getEvaluation().toLowerCase().contains(keyword) ||
                    p.getCertificat().toLowerCase().contains(keyword)) {
                filteredList.add(p);
            }
        }

        tableView.setItems(filteredList);
    }

    @FXML
    private void exporterCsv() {
        FileChooser fileChooser = new FileChooser();
        fileChooser.setTitle("Exporter en CSV");
        fileChooser.getExtensionFilters().add(new FileChooser.ExtensionFilter("CSV Files", "*.csv"));
        File file = fileChooser.showSaveDialog(tableView.getScene().getWindow());

        if (file != null) {
            try (FileWriter writer = new FileWriter(file)) {
                writer.write("ID Participation,ID Séminaire,Statut,Date Inscription,Évaluation,Certificat\n");
                for (Participation p : participationList) {
                    writer.write(p.getID_Participation() + "," +
                            p.getID_Seminaire() + "," +
                            p.getStatut() + "," +
                            p.getDate_inscription() + "," +
                            p.getEvaluation() + "," +
                            p.getCertificat() + "\n");
                }
                showAlert(Alert.AlertType.INFORMATION, "Export Réussi", "Les données ont été exportées avec succès.");
            } catch (IOException e) {
                showAlert(Alert.AlertType.ERROR, "Erreur", "Une erreur s'est produite lors de l'exportation.");
            }
        }
    }

    @FXML
    private void showAgendaPopup() {
        Stage popupStage = new Stage();
        popupStage.initModality(Modality.APPLICATION_MODAL);
        popupStage.setTitle("Agenda");

        Label agendaLabel = new Label("Upcoming Seminars:\n- Seminar A: 2023-10-15\n- Seminar B: 2023-11-20");
        VBox popupContent = new VBox(agendaLabel);
        popupContent.setPadding(new Insets(20));

        Scene popupScene = new Scene(popupContent, 300, 200);
        popupStage.setScene(popupScene);
        popupStage.showAndWait();
    }

    private void loadParticipations() {
        ParticipationDAO participationDAO = new ParticipationDAO();
        participationList.clear();
        participationList.addAll(participationDAO.getAllParticipations());
        tableView.setItems(participationList);
    }

    private void updateCharts() {
        updatePieChart();
        updateScatterChart();
    }

    private void updatePieChart() {
        // Clear any existing data
        pieChart.getData().clear();

        // Retrieve all participations from the DAO
        ParticipationDAO participationDAO = new ParticipationDAO();
        List<Participation> participations = participationDAO.getAllParticipations();

        // Count the number of participations for each status
        long confirmedCount = participations.stream()
                .filter(p -> p.getStatut().equalsIgnoreCase("présent"))
                .count();
        long pendingCount = participations.stream()
                .filter(p -> p.getStatut().equalsIgnoreCase("Inscrit"))
                .count();
        long cancelledCount = participations.stream()
                .filter(p -> p.getStatut().equalsIgnoreCase("en attente"))
                .count();


        // Create PieChart data objects for each status
        PieChart.Data confirmedData = new PieChart.Data("présent", confirmedCount);
        PieChart.Data pendingData   = new PieChart.Data("Inscrit", pendingCount);
        PieChart.Data cancelledData = new PieChart.Data("en attente", cancelledCount);


        // Add data to the PieChart
        pieChart.getData().addAll(confirmedData, pendingData, cancelledData);

        // Use Platform.runLater to style the slices after nodes are created
        Platform.runLater(() -> {
            for (PieChart.Data data : pieChart.getData()) {
                String status = data.getName().toLowerCase();
                if (status.equals("présent") || status.equals("présent")) {
                    data.getNode().setStyle("-fx-pie-color: green;");
                } else if (status.equals("Inscrit")) {
                    data.getNode().setStyle("-fx-pie-color: orange;");
                } else if (status.equals("en attente")) {
                    data.getNode().setStyle("-fx-pie-color: red;");
                }
                else {
                    data.getNode().setStyle("-fx-pie-color: grey;");
                }
            }
        });
    }


    private void updateScatterChart() {
        scatterChart.getData().clear();
        ParticipationDAO participationDAO = new ParticipationDAO();
        List<Participation> participations = participationDAO.getAllParticipations();

        XYChart.Series<String, Number> series = new XYChart.Series<>();
        series.setName("Participations");

        for (Participation p : participations) {
            series.getData().add(new XYChart.Data<>(p.getDate_inscription().toString(), p.getID_Seminaire()));
        }

        scatterChart.getData().add(series);
    }

    private void showAlert(Alert.AlertType alertType, String title, String message) {
        Alert alert = new Alert(alertType);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    @FXML
    private void statistiques(ActionEvent event) {
        // Récupération de la liste des participations via le DAO
        ParticipationDAO participationDAO = new ParticipationDAO();
        List<Participation> participations = participationDAO.getAllParticipations();

        // Comptage des statuts
        long presentCount = participations.stream()
                .filter(p -> p.getStatut().equalsIgnoreCase("présent"))
                .count();
        long inscritCount = participations.stream()
                .filter(p -> p.getStatut().equalsIgnoreCase("inscrit"))
                .count();
        long attenteCount = participations.stream()
                .filter(p -> p.getStatut().equalsIgnoreCase("en attente"))
                .count();

        // Création des données du PieChart
        ObservableList<PieChart.Data> pieChartData = FXCollections.observableArrayList(
                new PieChart.Data("Présent", presentCount),
                new PieChart.Data("Inscrit", inscritCount),
                new PieChart.Data("En attente", attenteCount)
        );

        // Création et configuration du PieChart
        PieChart pieChart = new PieChart(pieChartData);
        pieChart.setTitle("Statistiques des Participants par Statut");

        // Application d'une couleur spécifique à chaque tranche
        Platform.runLater(() -> {
            for (PieChart.Data data : pieChart.getData()) {
                String status = data.getName().toLowerCase();
                if (status.equals("présent")) {
                    data.getNode().setStyle("-fx-pie-color: green;");
                } else if (status.equals("inscrit")) {
                    data.getNode().setStyle("-fx-pie-color: blue;");
                } else if (status.equals("en attente")) {
                    data.getNode().setStyle("-fx-pie-color: orange;");
                } else {
                    data.getNode().setStyle("-fx-pie-color: grey;");
                }
            }
        });

        // Affichage du PieChart dans une nouvelle fenêtre
        Stage stage = new Stage();
        stage.setTitle("Statistiques des Participants");
        VBox root = new VBox(pieChart);
        root.setPadding(new Insets(20));
        Scene scene = new Scene(root, 600, 400);
        stage.setScene(scene);
        stage.initModality(Modality.APPLICATION_MODAL);
        stage.show();
    }

}